spring.application.name=api-gateway
server.port=9000

services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082

# TODO 4.9: Issuer URI of Keycloak realm for JWT token verification
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-realm

# Actuator: expose health endpoint
management.endpoints.web.exposure.include=health
